name: schedule

on:
  schedule:
    # KST 00:00 에 날짜 바뀔떄는 은행 점검 중이라서 제대로 작동하지 않는다.
    # 적당히 다음날 아침에 보면 새로운 금리가 반영되어있는걸 원한다
    # https://support.toss.im/faq/129?from=5&page=1 은행 점검시간 적당히 피해서 설정
    # UTC 16:00 = KST 01:00
    - cron: '0 16 * * *'
    - cron: '32 4 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 6
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: check
        working-directory: packages/cli
        run: pnpm build

      - name: schedule
        working-directory: packages/cli
        run: |
          pnpm cli -- region:fetch
          pnpm cli -- region:parse
          pnpm cli -- rate:fetch
          pnpm cli -- rate:parse
          pnpm cli -- report:write
          ls -alh data_summary
